wandb_version: 1

pooling_method:
  desc: null
  value: none
scheduler_kwargs-max_lr:
  desc: null
  value: 0.004793526800625575
_wandb:
  desc: null
  value:
    code_path: code/src/main.py
    python_version: 3.9.16
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687470801.629512
    t:
      1:
      - 1
      - 2
      - 3
      - 41
      - 51
      - 55
      2:
      - 1
      - 2
      - 3
      - 41
      - 51
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.9.16
      5: 0.15.4
      8:
      - 5
      - 9
