wandb_version: 1

disc_steps_per_gen_step:
  desc: null
  value: 0.2
gen_drift_decay:
  desc: null
  value: 0
max_pert:
  desc: null
  value: 0.01
pert_l1_decay:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    code_path: code/src/main.py
    python_version: 3.9.16
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1688073022.786083
    t:
      1:
      - 1
      - 41
      - 51
      - 55
      2:
      - 1
      - 41
      - 51
      - 55
      3:
      - 23
      - 37
      4: 3.9.16
      5: 0.15.4
      8:
      - 5
      - 9
